// Copyright (C) 2026  oito2
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package update

import (
	"context"
	"fmt"
	"io"

	"github.com/oito2/perci/internal/config"
	"github.com/oito2/perci/internal/distro"
	"github.com/oito2/perci/internal/executor"
	"github.com/oito2/perci/internal/ui"
)

// Options are the optional cleanups the "Atualizar Sistema" screen offers,
// both off by default (decided with the user on 2026-09-29): a plain
// update never deletes logs or removes packages on its own.
type Options struct {
	// CleanJournal vacuums journal entries older than 7 days.
	CleanJournal bool
	// Autoremove removes orphaned packages (apt/dnf autoremove) and unused
	// Flatpak runtimes.
	Autoremove bool
}

// Run updates the system: packages, snap and flatpak (when available),
// plus the cleanups opts enables.
//
// Progress reports through ui.Step, one call per top-level phase —
// package/snap/journal update (all privileged) count as a single phase
// (see below), flatpak (never privileged) is its own; only counted when
// present, so `total` never counts a phase that gets skipped.
//
// Every privileged command (package manager + snap + journalctl — flatpak
// never needs root, see updateFlatpak) runs as ONE authentication via
// executor.RunSudoSequence instead of a separate exe.Run per command:
// pkexec (the GUI's escalation path, executor.Executor.UsePolicyKit) has
// no session cache the way sudo does, so running each command separately
// would prompt for the admin password up to 7 times (5 apt-get + snap +
// journalctl) for a single "Atualizar Sistema" click. Per-command
// narration that would otherwise be a separate ui.Info right before each
// individual exe.Run is instead each PrivilegedStep's own Announce field
// (echoed from inside the single privileged shell script, so it still
// lands in the stream at the right moment) — plain text, not the app's
// styled ui.Info panel, since it's generated by the shell, not Go.
func Run(ctx context.Context, exe *executor.Executor, stdout io.Writer, opts Options) error {
	ui.PrintHeader(stdout, "Atualizar Sistema", distro.DisplayName())

	family := distro.Detect()
	if family == distro.Unknown {
		ui.Err(stdout, "Distribuição não suportada. Gerenciador de pacotes não reconhecido.")
		return fmt.Errorf("nenhum gerenciador de pacotes suportado encontrado (apt/dnf)")
	}
	ui.Info(stdout, "Distribuição detectada: "+family)

	steps, err := packageSteps(family, opts.Autoremove)
	if err != nil {
		ui.Err(stdout, err.Error())
		return err
	}

	hasSnap := exe.CommandAvailable(ctx, "snap")
	hasFlatpak := exe.CommandAvailable(ctx, "flatpak")
	hasJournal := exe.CommandAvailable(ctx, "journalctl")

	if hasSnap {
		steps = append(steps, executor.PrivilegedStep{
			Announce: "Atualizando Snaps...",
			Soft:     true, WarnMessage: "Falha ao atualizar snaps.",
			Name: "snap", Args: []string{"refresh"},
		})
	} else {
		ui.Info(stdout, "Snap não instalado. Etapa ignorada.")
	}
	if opts.CleanJournal && hasJournal {
		steps = append(steps, executor.PrivilegedStep{
			Announce: "Limpando logs antigos do journal...",
			Soft:     true, WarnMessage: "Falha ao limpar journal.",
			Name: "journalctl", Args: []string{"--vacuum-time=7d"},
		})
	}

	total := 1 // the privileged batch above (packages + snap + journal, whichever apply) always runs
	if hasFlatpak {
		total++
	}
	stepIdx := 0
	nextStep := func(label string) {
		stepIdx++
		ui.Step(stdout, stepIdx, total, label)
	}

	nextStep("Atualizando pacotes do sistema...")
	ui.Info(stdout, "Solicitando autenticação de administrador (uma única vez para as etapas acima)...")
	if err := exe.RunSudoSequence(ctx, executor.Options{Stdout: stdout, Stderr: stdout}, steps); err != nil {
		ui.Err(stdout, "Falha ao atualizar pacotes: "+err.Error())
		return err
	}

	if hasFlatpak {
		nextStep("Atualizando Flatpaks...")
		if err := updateFlatpak(ctx, exe, stdout, opts.Autoremove); err != nil {
			ui.Warning(stdout, "Falha ao atualizar flatpaks: "+err.Error())
		}
	} else {
		ui.Info(stdout, "Flatpak não instalado. Etapa ignorada.")
	}

	ui.Success(stdout, "Atualização finalizada com sucesso.")
	return nil
}

// aptEnv is the extra environment apt-get needs to never block on a TTY
// prompt (ex. a config-file conflict dialog) mid-batch.
var aptEnv = []string{"DEBIAN_FRONTEND=noninteractive"}

// packageSteps returns family's package-manager commands as
// executor.RunSudoSequence steps — Announce mirrors the ui.Info narration
// each step used to print separately, right before its own exe.Run call,
// back when this ran one privileged command at a time (see Run's doc
// comment for why that changed). full-upgrade alone covers what a
// separate apt-get upgrade used to do first.
func packageSteps(family string, autoremove bool) ([]executor.PrivilegedStep, error) {
	aptOpts := []string{"-o", "APT::Color=0", "-o", "Dpkg::Progress-Fancy=0", "-o", "Dpkg::Use-Pty=0"}
	switch family {
	case distro.Debian:
		steps := []executor.PrivilegedStep{
			{Announce: "Sincronizando lista de pacotes...", Env: aptEnv, Name: "apt-get", Args: append([]string{"update"}, aptOpts...)},
			{Announce: "Instalando atualizações...", Env: aptEnv, Name: "apt-get", Args: append([]string{"full-upgrade", "-y"}, aptOpts...)},
		}
		if autoremove {
			steps = append(steps, executor.PrivilegedStep{Announce: "Removendo pacotes desnecessários...", Env: aptEnv, Name: "apt-get", Args: append([]string{"autoremove", "-y"}, aptOpts...)})
		}
		return append(steps, executor.PrivilegedStep{Announce: "Limpando cache APT...", Env: aptEnv, Name: "apt-get", Args: []string{"autoclean", "-y"}}), nil
	case distro.Fedora:
		steps := []executor.PrivilegedStep{
			{Announce: "Atualizando pacotes DNF...", Name: "dnf", Args: []string{"upgrade", "--refresh", "-y"}},
		}
		if autoremove {
			steps = append(steps, executor.PrivilegedStep{Announce: "Removendo pacotes desnecessários...", Soft: true, WarnMessage: "Falha no dnf autoremove.", Name: "dnf", Args: []string{"autoremove", "-y"}})
		}
		return steps, nil
	default:
		return nil, fmt.Errorf("família de distribuição não suportada: %s", family)
	}
}

// Same reasoning as updateFlatpak below re: no separate "starting" ui.Info
// — flatpak is the only phase left that isn't part of the single
// privileged batch above (it never needs root), so its ui.Step call in
// Run is this phase's only announcement.
//
// The update has no --user/--system flag, so it covers both installations
// — apps installed outside Perci's configured scope included. Removing
// unused runtimes is the autoremove option's Flatpak half, in the
// configured scope.
func updateFlatpak(ctx context.Context, exe *executor.Executor, stdout io.Writer, autoremove bool) error {
	if !exe.CommandAvailable(ctx, "flatpak") {
		ui.Info(stdout, "Flatpak não instalado. Etapa ignorada.")
		return nil
	}
	opts := executor.Options{Stdout: stdout, Stderr: stdout, Env: []string{"TERM=dumb"}}
	if err := exe.Run(ctx, opts, "flatpak", "update", "--noninteractive", "-y"); err != nil {
		return fmt.Errorf("flatpak update: %w", err)
	}
	if !autoremove {
		return nil
	}
	if err := exe.Run(ctx, opts, "flatpak", "uninstall", "--noninteractive", config.FlatpakFlag(), "--unused", "-y"); err != nil {
		ui.Warning(stdout, "Falha ao remover flatpaks não utilizados: "+err.Error())
	}
	return nil
}
